spring:
  jpa:
    generate-ddl: true
    database: postgresql
    show-sql: true
    properties:
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
  datasource:
    url: jdbc:postgresql://${POSTGRESHOST}:${POSTGRESPORT}/${POSTGRESDATABASE}
    username: ${POSTGRESUSER}
    password: ${POSTGRESPASSWORD}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Brazil/East

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    packagesToScan: com.manager.controller
    use-root-path: true