#name: Test and Deploy
#
#on:
#  push:
#    branches: ["main"]
#
#jobs:
#  test:
#    name: Build without tests
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#          cache: maven
#
#      - name: Grant mvnw permission
#        run: chmod +x mvnw
#
#      - name: Build (skip tests)
#        run: ./mvnw clean package -DskipTests
#
#
#  deploy:
#    name: Deploy to Render
#    needs: test
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Trigger Render Deployment
#        run: |
#          curl -X POST \
#            -H "Accept: application/json" \
#            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
#            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys

name: Test and Deploy

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Build with tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Grant mvnw permission
        run: chmod +x mvnw

      # ðŸ‘‰ Agora rodando testes normalmente
      - name: Run tests
        run: ./mvnw test

      # ðŸ‘‰ Build completo sem pular testes
      - name: Build (with tests)
        run: ./mvnw clean package


  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
